version: "3.7"
services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ad_test
    container_name: ad_test-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ad_test

  npm:
    tty: true
    image: node:16.2.0
    container_name: ad_test-npm
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    entrypoint: ['npm']
    networks:
      - ad_test

  db:
    image: mysql:5.7
    container_name: ad_test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .docker/data/mysql:/var/lib/mysql
    networks:
      - ad_test

  nginx:
    image: nginx:alpine
    container_name: ad_test-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ad_test

networks:
  ad_test:
    driver: bridge
